[package]
name = "crypdatrs"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = "2.0.0"
fstrings = "0.2.3"
iced = "0.3.0"
ureq = "2.1.1"