[package]
name = "crypto_scan"
version = "0.1.0"
edition = "2018"

[dependencies]
colored = "2.0.0"
dotenv = "0.15.0"
fstrings = "0.2.3"
gladis = "1.0.1"
gio = "0.14.6"
gtk = "0.14.1"
reqwest = "0.11.4"
serde_json = "1.0.66"
ureq = "2.1.1"
