[package]
name = "crypdatrs"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.3"
colored = "2.0.0"
dotenv = "0.15.0"
fstrings = "0.2.3"
reqwest = "0.11.4"
pest = "2.1.3"
serde_json = "1.0.66"
